apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnsi-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnsi-portal-serviceaccount
  namespace: {{ .Release.Namespace }}
---
