# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
kind: Service
apiVersion: v1
metadata:
  name: cnsi-portal-service
  namespace: cnsi-system
spec:
  selector:
    cnsi-portal: portal
  ports:
  - protocol: TCP
    port: 3800
    targetPort: 3800
    nodePort: 30150
  type: NodePort